version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: undici
    versions:
    - 3.2.0
    - 3.3.0
    - 3.3.1
    - 3.3.3
    - 3.3.4
    - 3.3.5
  - dependency-name: autocannon
    versions:
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.1.0
  - dependency-name: fastify-error
    versions:
    - 0.3.0
  - dependency-name: yup
    versions:
    - 0.32.8
